(function () {

function createName(race, use_nickname){
	
	var nick_name_starts = ['Quivering', 'Artful', 'Tootful', 'Slobbery', 'Flatulent', 'Shivering', 'Blustery', 'Fickle', 'Dirty', 'Limping', 'Tattered', 'Sparkling', 'Folding', 'Mischievous', 'Petulant', 'Perturbed', 'Jibbly', 'Crafty', 'Filthy', 'Subversive', 'Sacrilegious', 'Offensive', 'Nubile', 'Sadistic', 'Provocative', 'Zany', 'Nurturing', 'Vicious', 'Vilified', 'Gleany', 'Urbane', 'Impish', 'Invulnerable', 'Venerable', 'Venereal', 'Opulent', 'Languished', 'Distorted', 'Derisive', 'Subversive', 'Subcutaneous', 'Ancient', 'Jocular', 'Agile', 'Ad Hominem', 'Schmaltzy', 'Foreign', 'Distended', 'Shoeless', 'Confused', 'Feigned', 'Fabled', 'Prophesized', 'Cursed', 'Curious', 'Callous', 'Unkind', 'Inbred', 'Inarticulate', 'Exemplary', 'Exorcised', 'Enchanted', 'Elder', 'Skittish', 'Frivolous', 'Fancy', 'Plumed', 'Berserked', 'Concave', 'Warbling', 'Intuitive', 'Introspective', 'Lactating', 'Serrated', 'Vigorous', 'Curt', 'Disappointed', 'Overbearing', 'Bulky', 'Spitting', 'Cunning', 'Chaotic', 'Vile', 'Hideous', 'Decadant', 'Frugal', 'Repulsive', 'Succulent', 'Blubbering', 'Whining', 'Malignant', 'Garbled', 'Impressionable', 'Underprivileged', 'Flooped', 'Domesticated', 'Impotent', 'Institutionalized'];
	
	var nick_name_ends = ['Fool', 'Race-Baiter', 'Weasel', 'Artist', 'Mule', 'Grad Student', 'Debtor', 'Mongoose', 'Hammer', 'Sea Turtle', 'War Wagon', 'Sow', 'Imp', 'Mistress', 'Lump', 'Pea-Shooter', 'Pickle', 'Belch', 'Fart Bag', 'Abyss', 'Emptiness', 'Crevice', 'Cad', 'Goose', 'Spirit', 'Stinker', 'Expeditor', 'Peacekeeper', 'Moth', 'Crow', 'Widow', 'Widow Maker', 'Pacesetter', 'Pacemaker', 'Magic Dragon', 'Heifer', 'Loris', 'Banshee', 'Duck', 'Whale', 'Manatee', 'Liberator', 'Marauder', 'Navigator', 'Sentinel', 'Show Pony', 'Shiksa', 'Mensch', 'Latke', 'Golem', 'Schmuck', 'Yutz', 'Guppy', 'Flounder', 'Potato', 'Yam', 'Gourd', 'Turd', 'Fiddler', 'Toot', 'Airhorn', 'Rooster', 'Clump', 'Orb', 'Go-Kart', 'Mosquito', 'Ant', 'Imbecile', 'Infant', 'Nymph', 'Otter', 'Worm', 'Jalopy', 'Lemon', 'Snowcone', 'Arsonist', 'Blimp', 'Night Terror', 'Plum', 'Bodice', 'Burka', 'Jitterbug', 'Bedbug', 'Squid', 'Sausage', 'Sea Cucumber', 'Poodle', 'Luddite', 'Onion Blossom', 'Twink', 'Gumball', 'Lentil', 'Turnip', 'Vapor', 'Donkey', 'Hen', 'Goat', 'Llama', 'Oyster', 'Toad', 'Parsnip', 'Ape', 'Trash', 'Piglet', 'Blueberry', 'Raspberry', 'Blob', 'Unicorn', 'Eunuch', 'Bobbin', 'Bumbershoot', 'Aglet', 'Opus', 'Ham Shack'];

	
	var dwarf_name_starts = ['Tor','Tol','Tal','Tur','Tar','Tul','Gur','Gar','Ul','Or','Ar','Ur','Dur','Dor','Dar','Bud','Bad','Gan','Gun','Rud','Rod','An','Un','Arig','Urig','Stan','Stun','Ston','Gor','Al','Dol','Ed','Grun','Har','Ig','Kaz','Los','Mor','Nil','Od','Pad','Rog','Stig','Trud','Trad','Trod','Ag','Bod','Dal','Erig','Gon','Rad','In','Kot','Lu','Pal','Rus','Stin','Ul','Yan','Yun','Yon','Ug','Kap','Tro','Tra','Tru','Uld','Ald','Old','Thor','Thur','Tho','Thu','Tha','Thy','Gyl','Gal','Gul','Gol','Bod','Bad','Bud','Bun','Ban','Bon','Byn','Mun','Man','Mon','Dim','Dum','Dam','Hun','Han','Hon','Hum','Ham','Hag','Hug','Hak','Huk','Hul','Hal','Hol','Gil','Gal','Bal','Gim','Gam','Gum','Gom','Gym','Glan','Glon','Glor','Baz','Thra','Thru','Thro','Thru','Ur','Whur','Yur',  'Al', 'Durinn', 'Khazad', 'Ori', 'Andvari', 'Eiken', 'Kheled', 'Shathur', 'Ann', 'Farin', 'Kibil', 'Skjald', 'Aust', 'Fili', 'Kili', 'Sognir', 'Anzanul', 'Fimbul', 'Litr', 'Suthri', 'Bal', 'Forn', 'Lofars', 'Thekkr', 'Baraz', 'Frar', 'Maeztr', 'Thrasir', 'Bard', 'Frosti', 'Marzabul', 'Thjf', 'Baruk', 'Fund', 'Mim', 'Thorinn', 'Blain', 'Gim', 'Nbli', 'Thror', 'Bofurr', 'Ginnar', 'Nar', 'Vargr', 'Bomburr', 'Glo', 'Nithi', 'Vestri', 'Bori', 'Gro', 'Nipingr', 'Viggr', 'Brand', 'Hannar', 'Nothri', 'Vind', 'Bund', 'Hepti', 'Nyi', 'Virfir', 'Dainn', 'Hor', 'Nyr', 'Vitr', 'Dolg', 'Horn', 'Oinn', 'Zinbar', 'Dufr', 'Jari', 'Onarr', 'Zirak', ];
	
	var dwarf_name_ends = ['le', 'hle', 'in', 'inn', 'i', 'is', 'nala', 'ri', 'u', 'rag','rum','adar','na','dill','bra','ga','ild','gra','ri','stra','dna','ilka','na','lrikka','ka','grit','k','grin','rukk','yar','sk','mar','muk','k','grym','s','ol','rym','ar','ur','dig','ilska','gruk','dryk','drak','druk','yur','yor','mak','grum','gun','gan','nu','no','mon','non','kda','kdu','al','yl','yk','yd','ad','ud','uksa','tra','vag','vog','vug','vig','vyg','oon','uri','bur','bar','bum','bor','ain','i','ar','rkk','um','min','til','tri','ond','lin','munn','rundd','rondd','rim','ni','im','din','rund','ak','lunn','rum','rom','ram','rain','ar','dri','dra','dru','drig','dryg','drug','vin','or','drik','gand','lond','ring','ster','thal','thic','grim','gur','gen','dak','gas','thic','or','oril','im','ym','aul','ent','ant','unt','var','ving','vyn'];

//these were taken from 
	var dwarf_last_name_starts = ['A', 'An', 'Ar', 'Az', 'B', 'Bel', 'Bar', 'Baz', 'Bof', 'Bol', 'D', 'Dar', 'Del', 'Dol', 'Dor', 'Dw', 'Duer', 'Dur', 'El', 'Er', 'Fal', 'Far', 'Gar', 'Gil', 'Gim', 'Glan', 'Glor', 'Har', 'Jar', 'Kil', 'Ma', 'Mor', 'Nal', 'Nor', 'Nur', 'O', 'Or', 'Ov', 'Rei', 'Th', 'Tho', 'Thr', 'Tor', 'Ur', 'Val', 'Von', 'Whur', 'Wer', 'Yur', 'A', 'An', 'Ar', 'Az', 'B', 'Bel', 'Bar', 'Baz', 'Bof', 'Bol', 'D', 'Dar', 'Del', 'Dol', 'Dor', 'Dw', 'Duer', 'Dur', 'El', 'Er', 'Fal', 'Far', 'Gar', 'Gil', 'Gim', 'Glan', 'Glor', 'Har', 'Jar', 'Kil', 'Ma', 'Mor', 'Nal', 'Nor', 'Nur', 'O', 'Or', 'Ov', 'Rei', 'Th', 'Tho', 'Thr', 'Tor', 'Ur', 'Val', 'Von', 'Whur', 'Wer', 'Yur', ];
	
	var dwarf_last_name_ends = ['aim', 'ain', 'ak', 'ar', 'auk', 'bere', 'bir', 'dak', 'dal', 'din', 'el', 'ent', 'erl', 'gal', 'gar', 'gan', 'gen', 'grim', 'gur', 'ias', 'i', 'ili', 'im', 'in', 'ir', 'kas', 'kral', 'lond', 'o', 'on', 'or', 'oril', 'rak', 'ral', 'ric', 'rid', 'rim', 'ring', 'ster', 'sun', 'ten', 'thal', 'then', 'thic', 'thur', 'ut', 'ur', 'urt', 'val', 'var', 'ack', 'ack', 'ack', 'ack', 'arr', 'arr', 'arr', 'arr', 'bek', 'bek', 'bek', 'bek', 'ral', 'cral', 'cral', 'cral', 'dar', 'dar', 'dar', 'duum', 'duum', 'duum', 'dukr', 'dukr', 'dukr', 'eft', 'eft', 'eft', 'erg', 'erg', 'erg', 'est', 'est', 'est', 'fik', 'fik', 'fik', 'gak', 'girn', 'girn', 'girn', 'gyth', 'hak', 'hak', 'hak', 'hig', 'hig', 'hig', 'jak', 'jyr', 'jyr', 'jyr', 'kak', 'kak', 'kak', 'krak', 'krak', 'krak', 'lagg', 'lagg', 'lagg', 'lode', 'lode', 'lode', 'lyr', 'lyr', 'lyr', 'malk', 'malk', 'malk', 'mek', 'mek', 'mek', 'nore', 'nore', 'nore', 'rak', 'rak', 'rak', 'ral', 'ral', 'ral', 'sten', 'sten', 'sten', 'tek', 'tek', 'tek', 'vir', 'vir', 'vir', 'zak', 'zak', 'zak', ];
	
	// var human_name_inners = ['all', 'sleeper', 'furious', 'breeze', 'oaken', 'glass', 'cloudy', 'blade', 'travelled', 'silver', 'shield', 'east', 'file', 'wedge', 'roaring', 'shadowvalley', 'great', 'ruddy', 'southone', 'burning', 'ancient', 'stooper', 'beloved', 'red', 'swift', 'master', 'eager', 'battleaxe', 'frosty', 'records', 'thief', 'axes', 'found', 'think', 'bold', 'black', 'fire', 'axel', 'boar', 'knave', 'deciever', 'corpse', 'wolf', 'bulging', 'glow', 'oldmoon', 'westone', 'borer', 'grow', 'pinch', 'spear', 'swordtorch', 'skilled', 'northone', 'windy', 'head', 'handle', 'newmoon', 'dyer', 'deadlike', 'high', 'new', 'wise', 'battle', 'horn', 'fearful', 'peak', 'nodder', 'warrior', 'starer', 'mountain',];
	
	
	
	var human_name_starts = ['Tom', 'Harry', 'Jim', 'Vito', 'Pete', 'Phil', 'Tony', 'Don', 'Steve', 'Ken', 'Evan', 'Carl', 'Jen', 'Ryan', 'Rick', 'Ralph', 'Arny', 'Al', 'Lou', 'Ned', 'Mike', 'Bob', 'Herb', 'Dan', 'Gary', 'Kim', 'Dave', 'Ed', 'Sue', 'Charlie', 'Chuck', 'Jane', 'Frank', 'James', 'Chris', 'Joe', 'Jack', 'Jake', 'Sam', 'Eric', 'Ben', 'April', 'Ronald', 'Mary', 'Lisa', 'Michelle', 'John', 'Daniel', 'Anthony', 'Patricia', 'Nancy', 'Laura', 'Robert', 'Paul', 'Kevin', 'Linda', 'Karen', 'Sarah', 'Michael', 'Mark', 'Jason', 'Barbara', 'Betty', 'Kimberly', 'William', 'Donald', 'Jeff', 'Elizabeth', 'Helen', 'Deborah', 'David', 'George', 'Jennifer', 'Sandra', 'Richard', 'Kenneth', 'Maria', 'Donna', 'Charles', 'Steven', 'Susan', 'Carol', 'Joseph', 'Edward', 'Margaret', 'Ruth', 'Thomas', 'Brian', 'Dorothy', 'Sharon', ];

	var human_name_ends = ['Smith', 'Anderson', 'Clark', 'Wright', 'Mitchell', 'Johnson', 'Thomas', 'Rodriguez', 'Lopez', 'Perez', 'Williams', 'Jackson', 'Lewis', 'Hill', 'Roberts', 'Jones', 'White', 'Lee', 'Scott', 'Turner', 'Brown', 'Harris', 'Walker', 'Green', 'Phillips', 'Davis', 'Martin', 'Hall', 'Adams', 'Campbell', 'Miller', 'Thompson', 'Allen', 'Baker', 'Parker', 'Wilson', 'Garcia', 'Young', 'Gonzalez', 'Evans', 'Moore', 'Martinez', 'Hernandez', 'Nelson', 'Edwards', 'Taylor', 'Robinson', 'King', 'Carter', 'Collins',];




	var goblin_first_name_starts = ['Chu','Cha','Cho','Dru','Dra','Dro','Gaw','Guw','Gow','Gho','Gha','Ghu','I','A','O','U','Ka','Ko','Ku','Lu','Lo','Law','Mo','Mu','Ma','Nu','No','Na','Vo','Zo','Po','Ro','Bu', 'Baw', 'Bho', 'Ku', 'Kho','Gha','Ghu','Va','Vu','Za','Zu','Pa','Pu','Ra','Ru',  'Ba', 'Bax', 'Dan', 'Fi', 'Fix', 'Fiz', 'Gi', 'Gix', 'Giz', 'Gri', 'Gree', 'Greex', 'Grex', 'Ja', 'Jax', 'Jaz', 'Jex', 'Ji', 'Jix', 'Ka', 'Kax', 'Kay', 'Kaz', 'Ki', 'Kix', 'Kiz', 'Klee', 'Kleex', 'Kwee', 'Kweex', 'Kwi', 'Kwix', 'Kwy', 'Ma', 'Max', 'Ni', 'Nix', 'No', 'Nox', 'Qi', 'Rez', 'Ri', 'Ril', 'Rix', 'Riz', 'Ro', 'Rox', 'So', 'Sox', 'Vish', 'Wi', 'Wix', 'Wiz', 'Za', 'Zax', 'Ze', 'Zee', 'Zeex', 'Zex', 'Zi', 'Zix', 'Zot'];
	
	var goblin_first_name_middles = ['b', 'ba', 'be', 'bi', 'd', 'da', 'de', 'di', 'e', 'eb', 'ed', 'eg', 'ek', 'em', 'en', 'eq', 'ev', 'ez', 'g', 'ga', 'ge', 'gi', 'ib', 'id', 'ig', 'ik', 'im', 'in', 'iq', 'iv', 'iz', 'k', 'ka', 'ke', 'ki', 'm', 'ma', 'me', 'mi', 'n', 'na', 'ni', 'q', 'qa', 'qe', 'qi', 'v', 'va', 've', 'vi', 'z', 'za', 'ze', 'zi', '', '', '', '', '', '', '', '', '', '', '', ''];
	
	var goblin_first_name_ends = ['ffy','rkus','bbus','wg','rg','rnk','vak','nthus','gmurch','gawg','gmaw','rch','rpus','gus','g','nk','unk','gun','rd','gmuff','gmoff','gmaff','gan','gon','hn','hb','b','pug','pag','pog','pun','pan','pon','pus','pas','pos','pow','paw','puw','pu','pa','po','rv','rf','h','vok','vuk','vokus','vakus','ggy','ddy','hy','gas','gos','rpos','rpas','vav','vov','vuv','bub','bab','bob','bous','vous','kous','kus','cchus','ff',  'ald', 'ard', 'art', 'az', 'azy', 'bit', 'bles', 'eek', 'eka', 'et', 'ex', 'ez', 'gaz', 'geez', 'get', 'giez', 'iek', 'igle', 'ik', 'il', 'in', 'ink', 'inkle', 'it', 'ix', 'ixle', 'lax', 'le', 'lee', 'les', 'lex', 'lyx', 'max', 'maz', 'mex', 'mez', 'mix', 'miz', 'mo', 'old', 'rax', 'raz', 'reez', 'rex', 'riez', 'tee', 'teex', 'teez', 'to', 'uek', 'x', 'xaz', 'xeez', 'xik', 'xink', 'xiz', 'xonk', 'yx', 'zeel', 'zil'];
	
	var goblin_last_name_starts = ['Wart','Sharp','Fire','Dark','Lick','Seven','Gap','Frost','Thistle','Bird','Moss','Hound','Broken','Wind','Ghost','Cinder','Hook','Bulb','Mud','Slash','Egg','Long','Spike','Knot','Pulp','Reef','Squid','Big','Scream','Spell','Rot','Pus', 'Two', 'Three','Five','Foul','Blood','Hatchet','Spear','Blade','Bile','Chirp','Bird','Dog','Wolf','Bear','Vile','Hate','Barb','Skunk','Blood','Snot','Savage','Fang','Slave','Rank','Vomit','Puke','Barf','Snort','Shade','Venom','Dark','Dread','Curse','Murder','Rant','Hate','Child','Fish','Horse', 'Bolt', 'Boom', 'Bot', 'Cog', 'Copper', 'Damp', 'Dead', 'Far', 'Fast', 'Fiz', 'Fizz', 'Fizzle', 'Fuse', 'Gear', 'Giga', 'Gold', 'Grapple', 'Grease', 'Greasy', 'Ground', 'Haggle', 'Hard', 'Knee', 'Leaf', 'Loose', 'Man', 'Mega', 'Money', 'Mud', 'Multi', 'Peddle', 'Pepper', 'Pick', 'Rocket', 'Rust', 'Salt', 'Salty', 'Sand', 'Scroll', 'Shadow', 'Sharp', 'Silver', 'Spark', 'Steam', 'Top', 'Wrench'];
	
	var goblin_last_name_ends = ['tongue','bumps','walker','wrap','toads','tooth','top','cruncher','fur','wood','gutter','whisper','bag','mask','seeker','head','rub','face','back','sucker','lung','snarl','spur','drool','hook','runner','slime','whistler','wing','barb','eater','scorch','spitter','spit','claw','maw','bone','skull','stink','chirp','talon','bristle','hunger','scale','reap','thorn','howl','moon','chewer','grinder','reek','stink','weed','yelp','whip','whipper','reaper','belch','belly','cutter','stabber','maw','gut','shredder','snapper','burner','swallower','snapper','snap','stab','cut','rip','grind', 'basher', 'blade', 'blast', 'blaster', 'bolt', 'bomb', 'boot', 'bottom', 'bub', 'button', 'buttons', 'cash', 'clamp', 'digger', 'feet', 'fingers', 'flare', 'fuel', 'fuse', 'gear', 'gleam', 'gob', 'grinder', 'grubber', 'hallow', 'hammer', 'head', 'knob', 'mine', 'nose', 'nozzle', 'pinch', 'pocket', 'pot', 'racket', 'rocket', 'screw', 'shatter', 'shiv', 'skimmer', 'snap', 'snipe', 'spark', 'sprocket', 'task', 'tongue', 'tooth', 'tweak', 'twister', 'volt', 'watts', 'well', 'wick', 'wizzle', 'wrench'];


	
	
	var elf_first_name_starts = ['A','Ai','Ae','Ca','Cao','Ce','Cae','Cea','Cy','Fa','Fae','Fe','Fi','Se','Sea','Si','Sa','She','Shi','Sha','Sha','Sio','Sia','Sia','Ro','Tu','Ta','Te','La','Li','Loe','Ly','Eo','Nua','Mae', 'Ra', 'Ri', 'Al', 'All', 'Aly', 'An', 'Am', 'As', 'Ay', 'Ar', 'Cy', 'Ca', 'E', 'E', 'El', 'Ely', 'Em', 'En', 'Er', 'Es', 'Ey', 'F', 'Fa', 'Fy', 'Fil', 'Fel', 'Fyl', 'Ga', 'Gal', 'Ha', 'He', 'Hy', 'I', 'Il', 'Ily', 'Ill', 'Iy', 'Ji', 'Ja', 'K', 'Ka', 'Ke', 'Ky', 'L', 'Lil', 'Lyl', 'Lel', 'La', 'Le', 'Ly', 'M', 'Ma', 'Me', 'My', 'Myt', 'Myth', 'Mor', 'Math', 'Mil', 'Myl', 'Mel', 'N', 'Na', 'Ne', 'Nyl', 'Nil', 'Nel', 'Nyt', 'Nyth', 'Ny', 'Re', 'Ra', 'Ry', 'S', 'Sa', 'Sil', 'Syl', 'Sel', 'Sh', 'Sha', 'She', 'Sy', 'Shyl', 'Th', 'Tha', 'The', 'Thel', 'Thyl', 'Thil', 'Thy', 'U', 'Uy', 'W', 'Wa', 'We', 'Y', 'Ya', 'Ye', 'Yl', 'Yll'];
	
	var elf_first_name_ends = ['nari','nara','ndaril','ndara','ndari','nmara','mara','laen','shaen','donaet','bahn','wan','wen','wyn','nwen','nwyn','raborn','phadion','n','nien','raion','ssion','nwë','maeion','dh','rthfael','dicca','dan','nainn','deyrn','mh','belinus','nbel','nwrig','ín','rraidhín','bhan','fael','rthfael','gan','lan','nbel','nnus','shlaine','delmid','theyrn','gaire','llan','chnaill','syll','llën','llyn','wyll','wylln','laryl','ldaril','ldara','phalion','raen','rail','rwyn','ryn',  'dris', 'ris', 'dral', 'dos', 'dlas', 'rion', 'idan', 'gyl', 'nul', 'gos', 'dras', 'dran', 'dryn', 'adros', 'dlass', 'lass', 'dlaess', 'dleass', 'laess', 'leass', 'thiel', 'engyl', 'annul', 'aenul', 'aenal', 'aenel', 'eanal', 'eanel', 'edon', 'adon', 'aedon', 'eadon', 'llian', 'llean', 'lian', 'lean', 'llaen', 'laen', 'nath', 'naeth', 'neath', 'shar', 'tharion', 'arion', 'erian', 'aerian', 'dent', 'elir', 'gorn', 'egorn', 'agorn', 'elor', 'ellor', 'aelor', 'aellor', 'elorn', 'ellorn', 'aelorn', 'aellorn', 'dren', 'odren', 'draen', 'odraen', 'adan', 'aedan', 'adaen', 'adean', 'draen', 'odraen', 'adarn', 'aedarn', 'adaern', 'adearn', 'drus', 'nrus', 'dryn', 'dan', 'andiir', 'diir', 'gyl', 'gyal', 'gyael', 'dir', 'umon', 'elar', 'aelar', 'ealar', 'oren', 'oraen', 'orean', 'las', 'thas', 'thaes', 'theas', 'sam', 'saem', 'seam', 'rand', 'ldor', 'dron', 'eth', 'gorm', 'rin', 'anas', 'anaes', 'aenas', 'anelle', 'dris', 'erias', 'thae', 'nra', 'nas', 'aste', 'ethil', 'driel', 'rieth', 'drieth', 'draeth', 'dreath', 'raeth', 'reath', 'ries', 'dries', 'draes', 'dreas', 'raes', 'reas', 'rai', 'rea', 'rae', 'raei', 'anai', 'laeth', 'leath', 'alas', 'aelas', 'alaes', 'aleas', 'aeleas', 'ealaes', 'aelleas', 'eallaes', 'allas', 'aellas', 'allaes', 'alleas', 'alias', 'alaeas', 'alath', 'aelath', 'alaeth', 'aleath', 'aeleath', 'ealaeth', 'aelleath', 'eallaeth', 'allath', 'aellath', 'allaeth', 'alleath', 'aliath', 'alaeath', 'aeith', 'eaith', 'ileath', 'ilaeth', 'aleath', 'illeath', 'illaeth', 'wen'];
	
	var elf_last_name_starts = ['Amber', 'Autumn', 'Bear', 'Black', 'Blade', 'Blue', 'Dark', 'Dawn', 'Dew', 'Dusk', 'Even', 'Far', 'Feather', 'Fog', 'Forest', 'Green', 'Leaf', 'Light', 'Luna', 'Mist', 'Moon', 'Moss', 'Night', 'Ocean', 'Rain', 'Rapid', 'Raven', 'Sage', 'Sea', 'Shade', 'Shadow', 'Shield', 'Silent', 'Silver', 'Sky', 'Spirit', 'Stag', 'Star', 'Still', 'Stone', 'Storm', 'Strong', 'Summer', 'Sun', 'Swift', 'Thunder', 'Tree', 'True', 'Void', 'Wild', 'Wind', 'Winter', 'Wood'];
	
	var elf_last_name_ends = ['wood','stone','moon','star','song','leaf','grass','tree','fruit','berry','sun','branch','twig','shrub','flower','bloom','petal','blossom','green','spring','bough','summer','autumn','winter','stream','river','lake','pond','creek','brooke','wind','breeze','bud','sky','cloud','oak','maple','cedar','ash','rowan','alder','aspen','beech','birch','hemlock','pine','elm','larch','willow','spruce','breath','sigh','light','bright','shine','bow','arrow','chant','year','rain','storm','gust','thunder','snow','shower','frost','ice','dew','hail','chill','warm','cold','heat','forest','marsh','grove','meadow','whisper','wish','dream','sweet','honey','caller','solar','lunar','mist','dawn','dusk','twilight','night','day','rainbow','echo','shadow','spirit','soul','soil','earth','season','north','east','south','west','child','lily','daisy','sprint','singer','dancer','chanter','keeper','watcher','mere','gold','black','green','white','down','wing','spear','thorn','horn','even','shiver','weather','silver','glow','myst','weaver','dove','mantle','glen','glade','cloak','thistle','mallow','fen','moss','wet','ear','eye','timber','thicket','wild','weald','loch','frost','brume','bush','bramble','briar','vine'];
	


	var nickname = '';

	if (use_nickname) nickname = ', The ' + nick_name_starts[Math.floor(Math.random() * nick_name_starts.length)] + ' ' + nick_name_ends[Math.floor(Math.random() * nick_name_ends.length)];

	if (race == 'dwarf') return dwarf_name_starts[Math.floor(Math.random() * dwarf_name_starts.length)] + dwarf_name_ends[Math.floor(Math.random() * dwarf_name_ends.length)] + ' ' + dwarf_last_name_starts[Math.floor(Math.random() * dwarf_last_name_starts.length)] + dwarf_last_name_ends[Math.floor(Math.random() * dwarf_last_name_ends.length)] + nickname;

	if (race == 'human') return human_name_starts[Math.floor(Math.random() * human_name_starts.length)] + ' ' + human_name_ends[Math.floor(Math.random() * human_name_ends.length)] + nickname;

	if (race == 'goblin') return goblin_first_name_starts[Math.floor(Math.random() * goblin_first_name_starts.length)] + goblin_first_name_middles[Math.floor(Math.random() * goblin_first_name_middles.length)] + goblin_first_name_ends[Math.floor(Math.random() * goblin_first_name_ends.length)] + ' ' + goblin_last_name_starts[Math.floor(Math.random() * goblin_last_name_starts.length)] + goblin_last_name_ends[Math.floor(Math.random() * goblin_last_name_ends.length)] + nickname;

	if (race == 'elf') return elf_first_name_starts[Math.floor(Math.random() * elf_first_name_starts.length)] + elf_first_name_ends[Math.floor(Math.random() * elf_first_name_ends.length)] + ' ' + elf_last_name_starts[Math.floor(Math.random() * elf_last_name_starts.length)] + elf_last_name_ends[Math.floor(Math.random() * elf_last_name_ends.length)] + nickname;

};

// amd
if (typeof define !== 'undefined' && define.amd) define(function(){return createName;});
//common js
if (typeof exports !== 'undefined') exports.createName = createName;
// browser
else if (typeof navigator !== 'undefined') this.createName = createName;
// nodejs
if (typeof module !== 'undefined') {
	module.exports = createName;
}

})();